Feature/products (#17) updated
* applied repository pattern: By utilizing the Repository pattern, we have achieved a clear separation of concerns, improved code organization.

* binded the class

* changed controller name from ProductModelController to ProductController

* product feature missing feature from stock (#16)

* views documentation added

* controller documentation added for IEnumerable vs List

* 1

* serilog configuuration

* autofac configuration

* grammar

* Feature/product (#6)

* renamed properties for product model

* migration and view file added,
error: need to ensure foreign key matches when inserting data

* insertion in product table working

* added exception handling

* modelState not at right place

* working: showing the category as list in frontend

* product entry working.
added: dropdown option for category in cshtml, annotation in model, and logged modelState validation failed reason

* Feature/product (#7)

* renamed properties for product model

* migration and view file added,
error: need to ensure foreign key matches when inserting data

* insertion in product table working

* added exception handling

* modelState not at right place

* working: showing the category as list in frontend

* product entry working.
added: dropdown option for category in cshtml, annotation in model, and logged modelState validation failed reason

---------

Co-authored-by: mohammad eunus <eunusur.rahaman.cse@ulab.edu.bd>

* wrong naming; corrected

* Feature/stock (#13)

* solved SqlNullValueException error

* working: added stock feature

* customer feature added (#14)

---------

Co-authored-by: AdminVai <83267669+MohammadEunusV2@users.noreply.github.com>

---------

Co-authored-by: AdminVai <83267669+MohammadEunusV2@users.noreply.github.com>